--- 
- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

- !ruby/object:Proc {}

